services:
  - type: web
    name: contentcraft-studio
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: data-protection-keys
      mountPath: /app/keys
      sizeGB: 1
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
    healthCheckPath: /health
    numInstances: 1
